// -*- mode: c++ -*-

/******		THIS FILE IS AUTOGENERATED, DO NOT EDIT !!	******/


#include <string>
using std::string; 

#include <version-info/GVersion.h>

const string GVersion::fGitBranch = "master";
const string GVersion::fGitTag = "v0.0.0-8-gaad2611";
const string GVersion::fCompileFlags = "c++ -std=c++17 -fPIC -std=c++17 -ggdb -g -o com-unit-tests com-unit-tests.o TestTCP.o TestUDP.o -L /home/perthi/logmaster/build/x86/lib -lm -ltestlib -lutilities -lcmdline -llogmaster -lreadline -lgtest -lpthread -lX11 -lcom -ltestlib -llogmaster -lcmdline";
const string GVersion::fLinkFlags = "-L /home/perthi/logmaster/build/x86/lib -lm -ltestlib -lutilities -lcmdline -llogmaster -lreadline -lgtest -lpthread -lX11 -lcom -ltestlib -llogmaster -lcmdline";
string GVersion::fOriginalExeName = "unknowne_exefile";
const string GVersion::fGitInfo = "__ Remote URLs:\n\
origin	git_github.com:perthi/logmaster.git (fetch)\n\
origin	git_github.com:perthi/logmaster.git (push)\n\
__ Remote Branches:\n\
  origin/HEAD -> origin/master\n\
  origin/master\n\
__ Local Branches:\n\
_ master\n\
__ Most Recent Commit:\n\
commit aad26116dafae956e0c40d6d4c0ad7ef386d94a2\n\
Author: Per Thomas <you_example.com>\n\
    _3\n\
Type 'git log' for more commits, or 'git show <commit id>' for full commit details.\n\
__ Configuration (.git/config):\n\
user.email=you_example.com\n\
core.repositoryformatversion=0\n\
core.filemode=true\n\
core.bare=false\n\
core.logallrefupdates=true\n\
remote.origin.url=git_github.com:perthi/logmaster.git\n\
remote.origin.fetch=+refs/heads/_:refs/remotes/origin/_\n\
branch.master.remote=origin\n\
branch.master.merge=refs/heads/master\n\
";


